// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package internal

import (
	"database/sql"
)

type AndroidMetadatum struct {
	Locale sql.NullString
}

type Feed struct {
	StreamID       int64
	SubscriptionID int64
}

type FeedGroup struct {
	Uid       int64
	Name      string
	IconID    int64
	SortOrder int64
}

type FeedGroupSubscriptionJoin struct {
	GroupID        int64
	SubscriptionID int64
}

type FeedLastUpdated struct {
	SubscriptionID int64
	LastUpdated    sql.NullInt64
}

type Playlist struct {
	Uid                  int64
	Name                 sql.NullString
	IsThumbnailPermanent int64
	ThumbnailStreamID    int64
	DisplayIndex         int64
}

type PlaylistStreamJoin struct {
	PlaylistID int64
	StreamID   int64
	JoinIndex  int64
}

type RemotePlaylist struct {
	Uid          int64
	ServiceID    int64
	Name         sql.NullString
	Url          sql.NullString
	ThumbnailUrl sql.NullString
	Uploader     sql.NullString
	DisplayIndex int64
	StreamCount  sql.NullInt64
}

type RoomMasterTable struct {
	ID           sql.NullInt64
	IdentityHash sql.NullString
}

type SearchHistory struct {
	CreationDate sql.NullInt64
	ServiceID    int64
	Search       sql.NullString
	ID           int64
}

type Stream struct {
	Uid                       int64
	ServiceID                 int64
	Url                       string
	Title                     string
	StreamType                string
	Duration                  int64
	Uploader                  string
	UploaderUrl               sql.NullString
	ThumbnailUrl              sql.NullString
	ViewCount                 sql.NullInt64
	TextualUploadDate         sql.NullString
	UploadDate                sql.NullInt64
	IsUploadDateApproximation sql.NullInt64
}

type StreamHistory struct {
	StreamID    int64
	AccessDate  int64
	RepeatCount int64
}

type StreamState struct {
	StreamID     int64
	ProgressTime int64
}

type Subscription struct {
	Uid              int64
	ServiceID        int64
	Url              sql.NullString
	Name             sql.NullString
	AvatarUrl        sql.NullString
	SubscriberCount  sql.NullInt64
	Description      sql.NullString
	NotificationMode int64
}
